### ISSUE TITLE
Show price of parking spot in the search results

### ISSUE THREAD

**Issue by hasbro17** [gamedayamenities/gameday_amenities#16]
**Description:**
Currently the price of a parking spot can only be seen after clicking on it, or viewing the pop up for it in the map. It might be more helpful for a user to be able to quickly glance at all the prices even if the results are sorted by price, rather than clicking on each spot to find out.

**Severity:**
Enhancement

**Comment by rschaefer2** [comment]
Fixed In Trunk. Link no longer in navigation bar. Accessible through tab in profile page
